# Generated by Django 4.1.6 on 2023-02-03 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nane',
            new_name='name',
        ),
    ]
