# Generated by Django 4.1.6 on 2023-02-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_nane_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('is_published', models.BooleanField()),
            ],
        ),
    ]
