# Generated by Django 4.1.6 on 2023-02-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_advertisement_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
