# Generated by Django 4.1.6 on 2023-02-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_alter_advertisement_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='author_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='advertisement',
            old_name='category_id',
            new_name='category',
        ),
    ]
